language: node_js
node_js:
- '14'

addons:
  ssh_known_hosts: 132.232.1.48

before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

# PM2 deploy
after_success:
  - npm i -g pm2 && pm2 deploy ecosystem.config.js prod update